//{{NO_DEPENDENCIES}}
//
#define VS_VERSION_INFO                 1
#define IDD_CREDENTIALS                 103
#define IDS_ERROR_INVALID_LICENSE       107
#define IDS_ERROR_SW2_ERROR             108
#define IDS_TAB_CONNECTION              109
#define IDS_TAB_CERTIFICATES            110
#define IDS_TAB_AUTHENTICATION          111
#define IDS_TAB_USERACCOUNT             112
#define IDS_ERROR_CERTIFICATES_SUCCESS  113
#define IDS_ERROR_CERTIFICATES_FAILED   114
#define IDS_ERROR_PROFILE_EXISTS        115
#define IDS_ERROR_SW2_ALERT             116
#define IDS_ERROR_PROFILE_DELETE        117
#define IDS_ERROR_PROFILE_DELETEDEFAULT 118
#define IDS_ERROR_SW2_CERTIFICATE       119
#define IDS_ERROR_CERTIFICATE_SUCCESS   120
#define IDS_ERROR_CERTIFICATE_FAILED    121
#define IDS_TAB_PROFILE                 122
#define IDS_TAB_LICENSE                 123
#define IDS_TAB_GINA                    124
#define IDS_ERROR_PROFILE_312           125
#define IDS_ERROR_CRYPTO_INVALID_CERTIFICATE 126
#define IDS_ERROR_EAP_INVALID_PACKET    127
#define IDS_ERROR_TLS_COMMUNICATION     128
#define IDS_ERROR_DEFAULT               129
#define IDS_ERROR_INNER_AUTHENTICATION  130
#define IDS_ERROR_PROFILE_NOROOTCA      131
#define IDS_LABEL_USERNAME              132
#define IDS_LABEL_PASSWORD              133
#define IDS_LABEL_REPASSWORD            134
#define IDS_LABEL_DOMAIN                135
#define IDS_LABEL_PROFILE               136
#define IDS_LABEL_OK                    137
#define IDS_LABEL_CANCEL                138
#define IDS_LABEL_PROFILE_DESC          139
#define IDS_LABEL_SAVECREDENTIALS       140
#define IDS_LABEL_CERT_HIERARCHY        141
#define IDS_LABEL_CERT_VIEW             142
#define IDS_LABEL_CERT_INSTALL          143
#define IDS_LABEL_CERT_INSTALLALL       144
#define IDS_LABEL_USEALTEROUTERID       145
#define IDS_LABEL_USEANONOUTERID        146
#define IDS_LABEL_SPECALTEROUTERID      147
#define IDS_LABEL_ENABLESESSRES         148
#define IDS_LABEL_USERCOMPUTER          149
#define IDS_LABEL_CONFIGURE             150
#define IDS_LABEL_EAPTYPE               151
#define IDS_LABEL_AUTHTYPE              152
#define IDS_LABEL_USECOMPCRED           153
#define IDS_LABEL_SERVERCERTLOCAL       154
#define IDS_LABEL_MS_EXTENSION          155
#define IDS_LABEL_RENEWIP               156
#define IDS_LABEL_ALLOWNEWCONN          157
#define IDS_LABEL_USEALTEREMPTYID       158
#define IDS_LABEL_DELETE                159
#define IDS_LABEL_NEW                   160
#define IDS_LABEL_ADVANCED              161
#define IDS_LABEL_VERIFYSERVERNAME      162
#define IDS_LABEL_VERIFYSERVERCERT      163
#define IDS_LABEL_TRUSTEDROOTCA         164
#define IDS_LABEL_ADDCA                 165
#define IDS_LABEL_REMOVECA              166
#define IDS_LABEL_AVAILABLEROOTCA       167
#define IDS_WINDOW_CONFIGURATION        168
#define IDS_WINDOW_NEWPROFILE           169
#define IDS_WINDOW_ADVANCED             170
#define IDS_WINDOWS_ADDCA               171
#define IDS_WINDOW_ADDCA                171
#define IDS_LABEL_PROMPT_USER           172
#define IDS_WINDOW_CREDENTIALS          173
#define IDS_WINDOW_UNTRUSTEDSERVER      174
#define IDS_WINDOW_IDENTITY             175
#define IDS_LABEL_IDENTITY              176
#define IDS_WINDOW_RESPONSE             177
#define IDS_LABEL_RESPONSE              178
#define IDS_ERROR_PASSWORD_MISMATCH     179
#define IDS_ERROR_REENTER_PASSWORD      180
#define IDC_VERIFY_SERVER_CHECK         1003
#define IDC_INNER_AUTH_COMBO            1004
#define IDC_WIRED_RADIO                 1005
#define IDC_CONFIG_TYPE_WIRED           1005
#define IDC_WIRELESS_RADIO              1006
#define IDC_CONFIG_TYPE_WIRELESS        1006
#define IDC_USER_COMPUTER_CRED_CHECK    1007
#define IDC_CONFIG_VERIFY_SERVER_DOMAIN 1007
#define IDC_CONFIG_VERIFY_SERVER_DOMAIN_LBL 1007
#define IDC_USERNAME                    1008
#define IDC_CONFIG_USE_ANONYMOUS_USERNAME 1009
#define IDC_CONFIG_USE_COMPUTER_PAP     1009
#define IDC_USERNAME3                   1010
#define IDC_USERNAME_LABEL              1011
#define IDC_PASSWORD_LABEL              1012
#define IDC_CONFIG_ENABLE_SESSION_RESUMPTION2 1012
#define IDC_CONFIG_RENEW_IP2            1012
#define IDC_CONFIG_USE_GINA             1012
#define IDC_DOMAIN_LABEL                1013
#define IDC_CRED_ERROR_LABEL            1014
#define IDC_TYPE_LABEL                  1015
#define IDC_TEMP_CHECK                  1015
#define IDC_COMPUTER_GROUP              1016
#define IDC_CONNECTION_GROUP            1017
#define IDC_CONFIG_USERNAME             1018
#define IDC_CONFIG_PASSWORD             1019
#define IDC_CONFIG_DOMAIN               1020
#define IDC_CONFIG_USERNAME_LABEL       1021
#define IDC_CONFIG_PASSWORD_LABEL       1022
#define IDC_CONFIG_DOMAIN_LABEL         1023
#define IDC_CONFIG_REG_KEY_LABEL        1028
#define IDC_CONFIG_REGKEY               1029
#define IDC_CONFIG_REG_ID_LABEL         1030
#define IDC_CONFIG_REG_ID               1031
#define IDC_IMPORT_LICENSE              1032
#define IDC_CONFIG_EAP                  1033
#define IDOK2                           1034
#define IDC_CONFIG_SERVER_DOMAIN        1050
#define IDC_CONFIG_ROOT_CA              1074
#define IDC_IPADDRESS1                  1078
#define IDC_IPADDRESS2                  1079
#define IDC_CONFIG_GINA_DOMAIN_LABEL2   1081
#define IDC_CONFIG_GINA_USE_SW2_GINA2   1082
