//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define VS_VERSION_INFO                 1
#define IDVIEWCERT                      4
#define IDINSTALLCERT                   5
#define IDINSTALLCERTS                  6
#define IDI_CERT_ICON_ERROR             7
#define IDD_IDENTITY                    101
#define IDB_LOGO                        102
#define IDD_SERVER_TRUST_DLG            102
#define IDD_CREDENTIALS                 103
#define IDD_CRED_DLG                    103
#define IDI_CERT_ICON                   103
#define IDD_CONFIG_CON_DLG              105
#define IDD_CONFIG_ADVANCED_DLG         106
#define IDD_CONFIG_USER_DLG             107
#define IDD_CONFIG_DLG                  109
#define IDD_CONFIG_AUTH_DLG             110
#define IDD_CONFIG_PROFILE_DLG          111
#define IDD_PROFILE_DLG                 112
#define IDD_PROFILE_NEW_DLG             113
#define IDD_CONFIG_CA2_DLG              115
#define IDD_CONFIG_CERT_DLG             115
#define IDD_CONFIG_CA_DLG               116
#define IDD_INSTALL_DLG                 118
#define IDC_VERIFY_SERVER_CHECK         1003
#define IDC_CONFIG_VERIFY_SERVER        1003
#define IDC_CONFIG_VERIFY_SERVER_CERT   1003
#define IDC_INNER_AUTH_COMBO            1004
#define IDC_CONFIG_INNER_AUTH           1004
#define IDC_CONFIG_VERIFY_MS_EXTENSION  1004
#define IDC_WIRED_RADIO                 1005
#define IDC_CONFIG_TYPE_WIRED           1005
#define IDC_CONFIG_INNER_EAP            1005
#define IDC_WIRELESS_RADIO              1006
#define IDC_CONFIG_TYPE_WIRELESS        1006
#define IDC_USER_COMPUTER_CRED_CHECK    1007
#define IDC_CONFIG_VERIFY_SERVER_DOMAIN 1007
#define IDC_CONFIG_VERIFY_SERVER_DOMAIN_LBL 1007
#define IDC_CONFIG_VERIFY_SERVER_NAME   1007
#define IDC_USERNAME                    1008
#define IDC_CRED_USERNAME               1008
#define IDC_CONFIG_USE_COMPUTER_CRED    1008
#define IDC_INSTALL_USERNAME            1008
#define IDC_CRED_PASSWORD               1009
#define IDC_CONFIG_USE_ANONYMOUS_USERNAME 1009
#define IDC_CONFIG_USE_COMPUTER_PAP     1009
#define IDC_INSTALL_PASSWORD            1009
#define IDC_USERNAME3                   1010
#define IDC_CRED_DOMAIN                 1010
#define IDC_CONFIG_ENABLE_SESSION_RESUMPTION 1010
#define IDC_CONFIG_ALLOW_NEW_CONNECTION 1010
#define IDC_INSTALL_PROFILE             1010
#define IDC_USERNAME_LABEL              1011
#define IDC_CRED_USERNAME_LABEL         1011
#define IDC_CONFIG_RENEW_IP             1011
#define IDC_INSTALL_USERNAME_LABEL      1011
#define IDC_PASSWORD_LABEL              1012
#define IDC_CRED_PASSWORD_LABEL         1012
#define IDC_CONFIG_INNER_EAP_LABEL      1012
#define IDC_CONFIG_ENABLE_SESSION_RESUMPTION2 1012
#define IDC_CONFIG_RENEW_IP2            1012
#define IDC_CONFIG_USE_GINA             1012
#define IDC_CONFIG_USE_ALTERNATE_EMPTY  1012
#define IDC_INSTALL_PASSWORD_LABEL      1012
#define IDC_DOMAIN_LABEL                1013
#define IDC_CRED_DOMAIN_LABEL           1013
#define IDC_INSTALL_PROFILE_LABEL       1013
#define IDC_INNER_AUTH_LABEL            1014
#define IDC_CERT_TREE                   1014
#define IDC_CRED_ERROR_LABEL            1014
#define IDC_INSTALL_PASSWORD2           1014
#define IDC_CONFIG_INNER_AUTH_LABEL     1014
#define IDC_TYPE_LABEL                  1015
#define IDC_TEMP_CHECK                  1015
#define IDC_INSTALL_DOMAIN_LABEL        1015
#define IDC_COMPUTER_GROUP              1016
#define IDC_CRED_SAVECREDENTIALS        1016
#define IDC_INSTALL_PASSWORD_LABEL2     1016
#define IDC_CONNECTION_GROUP            1017
#define IDC_CONFIG_USER_COMPUTER        1017
#define IDC_INSTALL_DOMAIN              1017
#define IDC_CONFIG_USERNAME             1018
#define IDC_CONFIG_USER_USERNAME        1018
#define IDC_CONFIG_PASSWORD             1019
#define IDC_CONFIG_USER_PASSWORD        1019
#define IDC_CONFIG_DOMAIN               1020
#define IDC_CONFIG_USER_DOMAIN          1020
#define IDC_CONFIG_USERNAME_LABEL       1021
#define IDC_CONFIG_USER_USERNAME_LABEL  1021
#define IDC_CONFIG_PASSWORD_LABEL       1022
#define IDC_CONFIG_USER_PASSWORD_LABEL  1022
#define IDC_CONFIG_DOMAIN_LABEL         1023
#define IDC_CONFIG_USER_DOMAIN_LABEL    1023
#define IDC_CONFIG_TAB                  1026
#define IDC_CONFIG_REG_KEY_LABEL        1028
#define IDC_CONFIG_REGKEY               1029
#define IDC_CONFIG_REG_ID_LABEL         1030
#define IDC_CONFIG_REG_ID               1031
#define IDC_IMPORT_LICENSE              1032
#define IDC_CONFIG_EAP                  1033
#define IDC_CONFIG_INNER_EAP_CONFIG     1033
#define IDC_CRED_DESCRIPTION            1033
#define IDC_PROFILE_DESCRIPTION         1033
#define IDC_CONFIG_COMP_USERNAME        1034
#define IDC_CONFIG_COMP_PASSWORD        1035
#define IDC_CONFIG_COMP_DOMAIN          1036
#define IDC_CONFIG_COMP_USERNAME_LABEL  1037
#define IDC_CONFIG_COMP_PASSWORD_LABEL  1038
#define IDC_CONFIG_COMP_DOMAIN_LABEL    1039
#define IDC_CONFIG_PROMPT_USER          1040
#define IDC_CONFIG_USER_ADVANCED        1041
#define IDC_CONFIG_PROFILE_CONFIGURE    1042
#define IDC_CONFIG_PROFILE_DELETE       1043
#define IDC_CONFIG_PROFILE_NEW          1044
#define IDC_CONFIG_PROFILES             1045
#define IDC_CONFIG_PROFILES_LABEL       1046
#define IDC_PROFILE_ID_LABEL            1047
#define IDC_PROFILE_ID                  1048
#define IDC_PROFILE_TAB                 1049
#define IDC_CONFIG_SERVER_DOMAIN        1050
#define IDC_CONFIG_SERVER_NAME          1050
#define IDC_CONFIG_SERVER_CERT_LOCAL    1051
#define IDC_CONFIG_TRUSTEDROOTCA        1053
#define IDC_CONFIG_ALTERNATE_OUTER      1056
#define IDC_CONFIG_USE_ALTERNATE_ANONYMOUS 1057
#define IDC_CONFIG_USE_ALTERNATE_OUTER  1058
#define IDC_CONFIG_USE_ALTERNATE_SPECIFY 1060
#define IDC_CONFIG_CERT_ADD             1070
#define IDC_CONFIG_ADDCERT_ADD          1071
#define IDC_CONFIG_CERT_REMOVE          1071
#define IDC_CONFIG_ROOTCA               1073
#define IDC_CONFIG_ROOT_CA              1074
#define IDC_IPADDRESS1                  1078
#define IDC_IPADDRESS2                  1079
#define IDC_CONFIG_GINA_DOMAIN_LABEL2   1081
#define IDC_CONFIG_GINA_USE_SW2_GINA2   1082
#define IDC_VERSION                     1085
#define IDC_CONFIG_TRUSTED_ROOTCA_LABEL 1086
#define IDC_CONFIG_AVAILABLE_ROOTCA_LABEL 1087
#define IDC_CERT_HIERARCHY              1088

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
